# Generated by Django 2.0.5 on 2018-05-19 16:32

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180519_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(null=True, upload_to=articles.models.Article.upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(null=True, upload_to=articles.models.Category.upload_path),
        ),
    ]
