# Generated by Django 2.0.5 on 2018-05-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180519_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
