# Generated by Django 2.0.5 on 2018-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articletranslation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletranslation',
            name='active',
        ),
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
